version: '3.3'

services:
  
  db:
    image: postgres:latest
    container_name: localpg 
    restart: always
    volumes: 
      - './data:/home/imports'
      - './init.sql:/docker-entrypoint-initdb.d/init.sql'
    environment:
      POSTGRES_PASSWORD: example

