version: '3.3'
services:
  db:
    image: postgres:latest
    restart: always
    volumes: 
      - './data:/home/imports'
      - './hw4.sql:/docker-entrypoint-initdb.d/hw4.sql'
    environment:
      POSTGRES_PASSWORD: example