version: '3.3'

services:
  
  db:
    image: postgres:latest
    container_name: localpg 
    restart: always
    ports:
      - 5432:5432
    networks:
      - hw5_net
    volumes: 
      - './data:/home/imports'
      - './init.sql:/docker-entrypoint-initdb.d/init.sql'
    environment:
      POSTGRES_PASSWORD: example

networks:
  hw5_net:
    external: true